/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as tests from "./tests";
export { Lock__factory } from "./Lock__factory";
export { Solmac__factory } from "./Solmac__factory";
